travis:
  secure:
    BINSTAR_TOKEN: fv65q2EqIQyL57JEvLIxrvt49MWKv6jkT6d7tA9l0rPXeWcpKzavdvuxV1lglCzfJV1LYokihKq07l9jZaK5hH/shgy20dpSZj8XvB41/MvDsTjOZKBNOmmDWlp0bdVzsVlttaKIzMhLUTuUgNBR1d63YUcLQQKkIfnSXUUj68RjSVVq4hu8r8dH71jClyv60cK4A5HLl4esXY/FBu2AKnFfJPDU6va/1LwJHFz+YjvktnidNYT6O/OJ0vL++qEKk7B97Cq5cZT710RU69sINH3svkk8aHSZOBpB2JOYDYDp0gvrxXRpu3DE7pKEafkbfQb/ZuShRea/l8N7jMrcUh9npDK9KKkhflMXOzyjF+88WsPDe9gIb7HYmjU/ZQ0WhyAWuenD2vgZj+f6CZJP1FviO4rdz5qyQzAODsw3qYSaujZQxczdjFrRDpQ43juVbwi+xTAgsgy+X1UpMLFc0xZNlFtbgMOpX8J6v+TXv2LaLOodg7z5lptNH5WJdoOBtBd514Ofc/H5FscNmNqFwe1No4QMLgKsjYDn/2ULFH1ALFs5RmmEkGu0M1PdGXie2lQONRN4v7/5YqlBSW9x1LB5CfCRt6QEHLA8u8mEVaL5EDKl++eeBIq0K41YYgWayAjyETpjX25FoCe+/e601OX18DsuIFNa1dnnnFEAeDg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
